baseURL       : https://asap.ucar.edu/
languageCode  : en-us
title         : "ASAP | Application Scalability And Performance"
theme         : ncar
enableGitInfo : true
summarylength : 25

menu:
  nav:
    - name      : About
      url       : about
      weight    : 10
    - name      : News
      url       : news
      weight    : 15
    - identifier: what
      name      : What we do
      weight    : 20
    - parent    : what
      name      : Software Projects
      url       : software
      weight    : 1
    - parent    : what
      name      : Research Projects
      url       : projects
      weight    : 1
    - parent    : what
      name      : Education
      url       : education
      weight    : 3
    - identifier: pp   
      name      : Publications & Presentations
      weight    : 30
    - parent    : pp
      name      : Publications
      url       : publications
      weight    : 10
    - parent    : pp
      name      : Presentations
      url       : presentations
      weight    : 20
    - identifier : collaborators
      name      : Collaborators
      weight    : 40
    - parent    : collaborators
      name      : SIParCS
      url       : siparcs
      weight    : 1
    - parent    : collaborators
      name      : Students & Visitors
      url       : visitors
      weight    : 2

# Site Params
params:
  pubcnt: ""
  name: ASAP
  dateFormat: "26 FEB 1994"
  description: "The ASAP (Application Scalability And Perfromance) section at the National Center for Atmospheric Research (NCAR)."
  author: "ASAP"
  email: "asap@ucar.edu"

  news:
    enable: true
    title: Recent News
    subtitle: 

  projects:
    enable: true
    title: Recent Projects
    subtitle: Some of our most recent projects

  footer:
    contactInfo:
      title  : Contact Info
      address: 1850 Table Mesa Dr.<br>Boulder, CO 80305
      email  : asap@ucar.edu

    sitemap:
      title: Sitemap
      column:
        - link:
          - name: About us
            url : about
          - name: Publications
            url : publications
          - name: Internships
            url : siparcs
        - link:
          - name: Software
            url : software
          - name: Research
            url : projects

